mysite/animes/urls.py
from . import views
from django.urls import path, include
from django.contrib import admin

app_name = 'animes'
urlpatterns = [
    # TODO: Has to combine user log-in index field into the default anime listing page
    path('', views.IndexView.as_view(), name = 'index'),
    path('recommendation/', views.recommendation, name = 'recommendtaion'),
    path('stat/', views.stat, name = 'stat'),
    path('profile/', views.profile, name = 'profile'),
    path('<int:anime_id>/', views.review_detail, name = 'detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name = 'results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
    path('sign_up/', views.sign_up, name = "sign_up"),
    path('rank_by_date/', views.rank_by_date, name = "rank_by_date"),
    path('rank_by_name/', views.rank_by_name, name = "rank_by_name"),
    path('rank_by_rating/', views.rank_by_rating, name = "rank_by_rating"),
    path('search_by_tag/', views.search_by_tag, name = "search_by_tag"),
    path('search/', views.search, name="search"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('animes/', include('animes.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

mysite/animes/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
# from django.contrib.auth.models import User

# Create your models here.
class User(AbstractUser):
    pass

class AnimeWork(models.Model):
    anime_id = models.AutoField(primary_key = True)
    anime_name = models.CharField(max_length = 300)
    anime_description = models.CharField(max_length = 10000)
    anime_avatar_url = models.CharField(max_length = 300, default = "www.google.com")
    anime_cover_image_url = models.CharField(max_length = 300, default = "www.google.com")
    anime_rating = models.DecimalField(max_digits = 4, decimal_places = 2)
    anime_airing_start_date = models.CharField(max_length = 50, default = '')
    anime_airing_end_date = models.CharField(max_length = 50, default = '')

    def __str__(self):
        return self.anime_name

class WatchList(models.Model):
    user = models.OneToOneField(
    User, on_delete = models.CASCADE,
    )
    anime_works = models.ManyToManyField(AnimeWork)

class WishList(models.Model):
    user = models.OneToOneField(
    User, on_delete = models.CASCADE,
    )
    anime_works = models.ManyToManyField(AnimeWork)

class Tag(models.Model):
    tag_name = models.CharField(max_length = 50)
    tag_anime_works = models.ManyToManyField(AnimeWork)
    def __str__(self):
        return self.tag_name

class ProductionCompany(models.Model):
    company_name = models.CharField(max_length = 50)
    company_anime_works = models.ManyToManyField(AnimeWork)

    def __str__(self):
        return self.company_name

class Review(models.Model):
    review_id = models.AutoField(primary_key = True)
    review_anime_id = models.ForeignKey(AnimeWork, on_delete=models.CASCADE)
    review_content = models.CharField(max_length = 10000, default = '')
    review_date_created = models.DateTimeField(auto_now_add = True)
    review_date_modified = models.DateTimeField(auto_now = True)
    review_upvotes = models.IntegerField(default = 0)
    reviewer_id = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering =  ['review_date_created']

    def __str__(self):
        return self.review_date_modified

class Reply(models.Model):
    reply_id = models.AutoField(primary_key = True)
    parent_review_id = models.ForeignKey(Review, on_delete=models.CASCADE)
    reply_date_created = models.DateTimeField(auto_now_add = True)
    reply_date_modified = models.DateTimeField(auto_now = True)
    replyer_id = models.ForeignKey(User, on_delete=models.CASCADE)
    reply_upvotes = models.IntegerField(default = 0)
    reply_content = models.CharField(max_length = 10000, default = '')

    class Meta:
        ordering = ['reply_date_created']

    def __str__(self):
        return self.review_date_modified

mysite/animes/forms.py
from .models import Review
from django import forms

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['review_id', 'review_content']

# class SearchForm(forms.Form):
#     keyword = forms.CharField(label='Key Word', max_length = 200)

mysite/animes/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core.paginator import Paginator


from .models import AnimeWork, User, Tag, ProductionCompany, Review
from .forms import ReviewForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from collections import Counter, defaultdict
import json
import numpy as np

# @login_required
# def index(request):
#     return render(request, 'animes/index.html')

def sign_up(request):
    context = {}
    form = UserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            login(request, user)
            return render(request, 'animes/index.html')
    context['form'] = form
    return render(request, 'animes/sign_up.html', context)

def search(request):
    context = {}
    keyword = request.GET['keyword']
    selected_animes = AnimeWork.objects.filter(anime_name__icontains=keyword)
    paginator = Paginator(selected_animes, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context['object_list'] = page_obj
    context['page_obj'] = page_obj
    context['tags'] = Tag.objects.all()
    return render(request, 'animes/index.html', context)

def search_by_tag(request):
    context = {}
    tag_info = request.GET['tag_info']
    selected_animes = AnimeWork.objects.filter(tag__tag_name__contains=tag_info)
    paginator = Paginator(selected_animes, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context['object_list'] = page_obj
    context['page_obj'] = page_obj
    context['tags'] = Tag.objects.all()
    return render(request, 'animes/index.html', context)

def rank_by_date(request):
    context = {}
    all_animes = AnimeWork.objects.all().order_by('anime_airing_start_date')[:60]
    paginator = Paginator(all_animes, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context['object_list'] = page_obj
    context['page_obj'] = page_obj
    context['tags'] = Tag.objects.all()
    return render(request, 'animes/index.html', context)

def rank_by_rating(request):
    context = {}
    all_animes = AnimeWork.objects.all().order_by('-anime_rating')[:60]
    paginator = Paginator(all_animes, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context['object_list'] = page_obj
    context['page_obj'] = page_obj
    context['tags'] = Tag.objects.all()
    return render(request, 'animes/index.html', context)

def rank_by_name(request):
    context = {}
    all_animes = AnimeWork.objects.all().order_by('anime_name')[:60]
    paginator = Paginator(all_animes, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context['object_list'] = page_obj
    context['page_obj'] = page_obj
    context['tags'] = Tag.objects.all()
    return render(request, 'animes/index.html', context)

@login_required
def recommendation(request):
    context = {}
    user = request.user
    anime_watch_list = [e.anime_name for e in user.watchlist.anime_works.all()]
    anime_wish_list = [e.anime_name for e in user.watchlist.anime_works.all()]
    recommendation = None
    # If the user does not have any previous watching history, recommend him/her
    # the top 10 animes with the hightest rating
    if len(anime_watch_list) == 0 and len(anime_wish_list) == 0:
        recommendation = AnimeWork.objects.all().order_by('anime_rating')[:10]
        context['recommendation'] = recommendation
        return render(request, 'animes/recommendation.html', context)
    wish_tag = Counter()
    watch_tag = Counter()
    tag_score = defaultdict(int)
    for anime in anime_wish_list:
        wish_tag.update([t.tag_name for t in Tag.objects.filter(tag_anime_works__anime_name__icontains=anime)])
    for anime in anime_watch_list:
        watch_tag.update([t.tag_name for t in Tag.objects.filter(tag_anime_works__anime_name__icontains=anime)])
    wish_tag = dict(wish_tag)
    watch_tag = dict(watch_tag)
    for tag in wish_tag.keys():
        tag_score[tag] += wish_tag[tag] * 2
    for tag in watch_tag.keys():
        tag_score[tag] += watch_tag[tag]
    # sample two categories of animes based on the weighted tag score
    tags = list(tag_score.keys())
    normalization_const = sum([v for k, v in tag_score.items()])
    probs = []
    for t in tags:
        probs.append(tag_score[t] * 1.0 / normalization_const)
    recommended_tags = np.random.choice(tags, 2, p = probs).tolist()

    recommendation = AnimeWork.objects.exclude(anime_name__in=anime_watch_list).exclude(anime_name__in=anime_wish_list) \
    .filter(tag__tag_name__in=recommended_tags).order_by('-anime_rating')[:5]
    context['recommendation'] = recommendation

    return render(request, 'animes/recommendation.html', context)

@login_required
def stat(request):
    context = {}
    user = request.user
    # user_2 = User.objects.get(username='Kai')
    # print('user_2', user_2.__dict__)
    # print('watch_list', user_2.watchlist)
    # print('user', user.__dict__)
    wish_list_anime = [e.anime_name for e in user.wishlist.anime_works.all()]
    watch_list_anime = [e.anime_name for e in user.watchlist.anime_works.all()]
    wish_tag = Counter()
    watch_tag = Counter()
    wish_company = Counter()
    watch_company = Counter()
    for anime in wish_list_anime:
        wish_tag.update([t.tag_name for t in Tag.objects.filter(tag_anime_works__anime_name__icontains=anime)])
        wish_company.update([c.company_name for c in ProductionCompany.objects.filter(company_anime_works__anime_name__icontains=anime)])
    for anime in watch_list_anime:
        watch_tag.update([t.tag_name for t in Tag.objects.filter(tag_anime_works__anime_name__icontains=anime)])
        watch_company.update([c.company_name for c in ProductionCompany.objects.filter(company_anime_works__anime_name__icontains=anime)])
    json_wish_tag = json.dumps([{'tag_name' : key, 'count' : value} for key, value in wish_tag.items()])
    json_watch_tag = json.dumps([{'tag_name' : key, 'count' : value} for key, value in watch_tag.items()])
    context['json_wish_tag'] = json_wish_tag
    context['json_watch_tag'] = json_watch_tag
    json_wish_company = json.dumps([{'company_name' : key, 'count' : value} for key, value in wish_company.items()])
    json_watch_company = json.dumps([{'company_name' : key, 'count' : value} for key, value in watch_company.items()])
    context['json_wish_company'] = json_wish_company
    context['json_watch_company'] = json_watch_company
    # print('json', json_watch_company)
    return render(request, 'animes/stat.html', context)

@login_required
def profile(request):
    return render(request, 'animes/profile.html')

class IndexView(generic.ListView):
    template_name = 'animes/index.html'
    model = AnimeWork
    paginate_by = 16
    # context_object_name = 'latest_question_list'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['tags'] = Tag.objects.all()
        return context

    def get_queryset(self):
        # print(AnimeWork.objects.all()[:30])
        return AnimeWork.objects.all()

class DetailView(generic.DetailView):
    model = AnimeWork
    template_name = 'animes/detail.html'

class AnimeWorkView(generic.DetailView):
    model = AnimeWork
    template_name = 'animes/detail.html'

class UserView(generic.DetailView):
    model = User
    template_name = 'animes/user.html'

@login_required
def review_detail(request, anime_id):
    template_name = 'animes/detail.html'
    anime_work = get_object_or_404(AnimeWork, pk = anime_id)
    reviews = anime_work.review_set.all()
    user = request.user
    new_review = None

    if request.method == 'POST':
        review_form = ReviewForm(data = request.POST)
        if review_form.is_valid():
            new_review = review_form.save(commit = False)
            new_review.review_anime_id = anime_work
            new_review.reviewer_id = user
            new_review.save()
    else:
        review_form = ReviewForm()
    return render(request, template_name, {
    'animework' : anime_work, 'reviews' : reviews, 'new_review' : new_review, 'review_form' : review_form
    })

mysite/animes/templates/animes/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>Django Central</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
      <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">About</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Policy</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Copyright &copy; Django Central</p>
        </footer>
    </body>
</html>

mysite/animes/templates/animes/detail.html
{% extends 'animes/my_base.html' %}

{% block content %}

{% comment %}
<h1> {{ animework.anime_name }} </h1>
{% csrf_token %}
<ul>
{% for review in animework.review_set.all %}
  <li>{{ review.review_content }}</li>
{% endfor %}
</ul>
{% endcomment %}

<style>
      body {
      font-family: "Roboto", sans-serif;
      font-size: 17px;
      background-color: #fdfdfd;
  }
  .shadow {
      box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
  }
  .btn-danger {
      color: #fff;
      background-color: #f00000;
      border-color: #dc281e;
  }
  .masthead {
      background: #3398E1;
      height: auto;
      padding-bottom: 15px;
      box-shadow: 0 16px 48px #E3E7EB;
      padding-top: 10px;
  }
</style>



<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left top">
      <div class="card-body">
        <h1>{% block title %} {{ animework.anime_name }} {% endblock title %}</h1>
        <p class="card-text ">{{ animework.anime_description | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'animes/sidebar.html' %} {% endblock sidebar %}
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>Reviews</h2>

        {% for review in animework.review_set.all %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            <span class=" text-muted font-weight-normal">
              {{ review.review_date_created }}
            </span>
          </p>
          {{ review.review_content | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_review %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a Review</h3>
        <form method="post" style="margin-top: 1.3em;">
          {% csrf_token %}
          {{ review_form.as_p }}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

mysite/animes/templates/animes/index.html
{% extends 'animes/my_base.html' %}

{% block content %}

<div class="modal-body row">
  <div class="col-md-9">
    <!-- Your first column here -->
    <div class="row justify-content-end">
      <a href="/animes/rank_by_rating" class="col-1 px-1 mx-1 my-1">Rank By Rating</a>
      <a href="/animes/rank_by_name" class="col-1 px-1 mx-1 my-1">Rank By Name</a>
      <a href="/animes/rank_by_date" class="col-1 px-1 mx-1 my-1">Rank By Date</a>
    </div>
    <ul class="list-group list-group-flush">
      <!-- <li class="list-group-item">Cras justo odio</li>
      <li class="list-group-item">Dapibus ac facilisis in</li>
      <li class="list-group-item">Morbi leo risus</li>
      <li class="list-group-item">Porta ac consectetur ac</li>
      <li class="list-group-item">Vestibulum at eros</li> -->
      {% for animework in object_list %}
        <a href="/animes/{{ animework.anime_id }}" class="list-group-item list-group-item-action list-group-item-action"> {{ animework.anime_name }} <br>
          <span>{{ animework.anime_airing_start_date }} / {{ animework.anime_rating}} /
             {% for company in animework.productioncompany_set.all|slice:":3" %}
              {% if forloop.last %}
                {{ company.company_name }}
              {% else %}
                {{ company.company_name}};
              {% endif %}
             {% endfor %} /

             {% for tag in animework.tag_set.all|slice:":5" %}
              {% if forloop.last %}
                {{ tag.tag_name }}
              {% else %}
                {{ tag.tag_name}};
              {% endif %}
             {% endfor %}
          </span>
        </a>
      {% endfor %}
    </ul>

    <div class="pagination my-2">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
  </div>
  <div class="col-md-3 my-5">
    <h3>Tags</h3>
    <form method="get" action="/animes/search_by_tag/">
      {% for tag in tags %}
        <button type="submit" value="{{ tag.tag_name }}" name="tag_info" class="btn btn-primary btn-lg mx-1 my-1" role="button" aria-pressed="true">{{ tag.tag_name }}</button>
      {% endfor %}
    </form>
  </div>
</div>
{% endblock content %}

mysite/animes/templates/animes/my_base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    {% block link %}
    {% endblock link %}

    <title>AnimeRecSite</title>

    {% block style %}
    {% endblock style %}
  </head>

  <body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">AnimeRecSite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/animes">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/animes/stat/">Statistics</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/animes/recommendation/">Recommendations</a>
          </li>
        </ul>
        <form action="/animes/search/" method="get" class="form-inline my-2 my-lg-0">
          <input name = "keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          <div class="dropdown">
            {% if user.is_authenticated %}
              <button class="btn btn-secondary dropdown-toggle my-2 mx-2" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Hi, {{ user.username }}
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="/animes/profile">Profile</a>
                <a class="dropdown-item" href="#">Notificaiton</a>
                <a class="dropdown-item" href="/accounts/logout">Sign Out</a>
              </div>
            {% else %}
              <button class="btn btn-secondary dropdown-toggle my-2 mx-2" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Visitor
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="/accounts/login">Sign In</a>
                <a class="dropdown-item" href="#">Sign Up</a>
              </div>
            {% endif %}
          </div>
        </form>
      </div>
    </nav>

    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}

  </body>
</html>

mysite/animes/templates/animes/recommendation.html
{% extends 'animes/my_base.html' %}

{% load static %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'animes/css/style.css' %}">
{% endblock link %}

<!-- <head>
<style>
  body {
    background: white url("images/recommendation_background.jpg") no-repeat;
  }
</style>
</head> -->

{% block content %}

<!-- Button trigger modal -->
<div class="d-flex justify-content-center align-self-center">
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Get Your Recommendations
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Your Recommendations</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="list-group-flush">
          {% for rec in recommendation %}
            <li class="list-group-item mx-2 my-2">
              <a href="/animes/{{ rec.anime_id }}">{{ rec.anime_name }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

mysite/animes/templates/animes/sidebar.html
{% block sidebar %}

{% load static %}

<body>
<script src="{% static 'animes/js/add_ons.js'%}"></script>

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

        .star-rating {
          line-height:32px;
          font-size:1.25em;
        }

        .star-rating .fa-star{color: yellow;}
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">Rate this Anime</h5>
    <div class="card-body">
        <p class="card-text">Rating: {% block rating %} {% endblock rating %} </p>
        <a href="https://djangocentral.com/building-a-blog-application-with-django"
           class="btn btn-danger">Know more!</a>
        <div class="star-rating">
           <span class="fa fa-star-o" data-rating="1"></span>
           <span class="fa fa-star-o" data-rating="2"></span>
           <span class="fa fa-star-o" data-rating="3"></span>
           <span class="fa fa-star-o" data-rating="4"></span>
           <span class="fa fa-star-o" data-rating="5"></span>
           <input type="hidden" name="whatever1" class="rating-value" value="2.56">
       </div>
     </div>
   </div>
 </div>
 </body>

<script>
  var $star_rating = $('.star-rating .fa');

  var SetRatingStar = function() {
    return $star_rating.each(function() {
      if (parseInt($star_rating.siblings('input.rating-value').val()) >= parseInt($(this).data('rating'))) {
        return $(this).removeClass('fa-star-o').addClass('fa-star');
      } else {
        return $(this).removeClass('fa-star').addClass('fa-star-o');
      }
    });
  };

  $star_rating.on('click', function() {
    $star_rating.siblings('input.rating-value').val($(this).data('rating'));
    return SetRatingStar();
  });

  SetRatingStar();
  $(document).ready(function() {

  });
</script>
{% endblock sidebar %}